### ISSUE TITLE
容器之间使用 127.0.0.1 连接 例子。容器通信方式：共享指定容器的网络空间

### ISSUE THREAD

**Issue by jingjingxyk** [jingjingxyk/swoole-cli#57]
```yaml
version: "3"
services:
    pause:
        image: gcr.io/google-containers/pause-amd64:3.1
        # image: alpine:latest
        # command: [ 'tail', '-f','/dev/null' ]
        restart: always
        container_name: pause
        ports:
            - "80:80"
            - "443:443"
    nginx:
        image: nginx:alpine
        network_mode: 'service:pause'
        depends_on:
            - pause
    php-fpm:
        image: phpswoole/php:8.1-alpine
        depends_on:
            - pause
        network_mode: 'service:pause'
 
```
